<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BoxPlanLib.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.OrTools" Version="9.12.4544" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoxPlanLib\BoxPlanLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\BoxPlanLib\sample-plans\**\*.yml"
             Link="sample-plans\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
